from __future__ import annotations

import re
import unittest
from pathlib import Path

from scripts import check_public_safety


ROOT = Path(__file__).resolve().parents[1]


class RepositoryQualityTests(unittest.TestCase):
    def test_public_readmes_and_architecture_do_not_publish_stale_status(self) -> None:
        readmes = [
            (ROOT / "README.md").read_text(encoding="utf-8"),
            (ROOT / "README_EN.md").read_text(encoding="utf-8"),
        ]
        for readme in readmes:
            with self.subTest(readme=readme[:32]):
                self.assertNotIn("363 passed", readme)

        architecture = (
            ROOT
            / "docs"
            / "implementation"
            / "echobot-architecture-data-flow-2026-05-09.md"
        ).read_text(encoding="utf-8")
        self.assertIn("SessionApplicationService", architecture)
        self.assertNotIn("sessions.py` 還需要抽 application service", architecture)

    def test_runtime_and_test_dependencies_use_compiled_lock_files(self) -> None:
        runtime_input = ROOT / "requirements.in"
        runtime_lock = ROOT / "requirements.txt"
        test_input = ROOT / "requirements-dev.in"
        test_lock = ROOT / "requirements-dev.txt"

        for path in (runtime_input, runtime_lock, test_input, test_lock):
            self.assertTrue(path.is_file(), path)

        self.assertIn(
            "autogenerated by uv",
            runtime_lock.read_text(encoding="utf-8").lower(),
        )
        self.assertIn("sherpa-onnx-core==", runtime_lock.read_text(encoding="utf-8"))
        self.assertIn(
            "autogenerated by uv",
            test_lock.read_text(encoding="utf-8").lower(),
        )
        self.assertIn("pytest==", test_lock.read_text(encoding="utf-8"))
        self.assertIn("playwright==", test_lock.read_text(encoding="utf-8"))
        self.assertIn("pip-audit==", test_lock.read_text(encoding="utf-8"))

    def test_container_publication_is_gated_by_reusable_ci(self) -> None:
        ci = (ROOT / ".github" / "workflows" / "ci.yml").read_text(
            encoding="utf-8",
        )
        container = (ROOT / ".github" / "workflows" / "container.yml").read_text(
            encoding="utf-8",
        )

        self.assertIn("workflow_call:", ci)
        self.assertIn("requirements-dev.txt", ci)
        self.assertIn("scripts/browser_smoke.py", ci)
        self.assertIn("python -m pip_audit", ci)
        self.assertIn("--requirement requirements.txt", ci)
        self.assertIn("--no-deps", ci)
        self.assertIn("--disable-pip", ci)
        self.assertIn("Container runtime smoke", ci)
        self.assertIn("docker save echobot-web-mobile:ci", ci)
        self.assertIn("actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a", ci)
        self.assertIn("git diff --check\n", ci)
        self.assertNotIn("git diff --check HEAD", ci)
        self.assertIn("verify:", container)
        self.assertIn("uses: ./.github/workflows/ci.yml", container)
        self.assertIn("needs: verify", container)
        self.assertIn(
            "actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c",
            container,
        )
        self.assertIn("docker load --input", container)
        self.assertNotIn("docker build", container)

    def test_public_safety_scan_covers_tracked_workflows_and_common_tokens(self) -> None:
        self.assertFalse(check_public_safety._should_skip_secret_scan(".github/workflows/ci.yml"))
        self.assertFalse(check_public_safety._should_skip_secret_scan("echobot/skills/example.md"))

        github_token = "gh" + "p_" + ("A" * 36)
        aws_key = "AK" + "IA" + ("A" * 16)
        discord_token = ("A" * 24) + "." + ("B" * 6) + "." + ("C" * 27)
        samples = {
            "github_token": github_token,
            "aws_access_key": aws_key,
            "discord_bot_token": discord_token,
        }
        for pattern_name, sample in samples.items():
            with self.subTest(pattern_name=pattern_name):
                self.assertRegex(
                    sample,
                    check_public_safety.SCANNED_SECRET_PATTERNS[pattern_name],
                )

        source = (ROOT / "scripts" / "check_public_safety.py").read_text(
            encoding="utf-8",
        )
        self.assertIsNone(re.search(r"ghp_[A-Za-z0-9]{36}", source))


if __name__ == "__main__":
    unittest.main()
